FROM ruby:2.7.1-alpine

RUN apk --update add build-base nodejs tzdata postgresql-dev postgresql-client libxslt-dev libxml2-dev

WORKDIR /app

COPY Gemfile .
RUN bundle install
COPY . .
CMD ["rails", "server", "-b", "0.0.0.0"]
