version: '3'
services:
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=postgres_password
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:alpine
  api:
    depends_on:
      - postgres
      - redis
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - .:/app
    environment:
      - DB_USERNAME=postgres
      - DB_HOST=postgres
      - DB_NAME=postgres
      - DB_PASSWORD=postgres_password
      - JWT_SECRET=secret
      - REDIS_URL=redis://redis:6379
    ports:
      - '3000:3000'

volumes:
  db_data:
